# MkDocs configuration for Hako-Core 4U Server Chassis documentation
site_name: Hako-Core 4U Server Chassis User Manual
site_description: Complete user manual for the Hako-Core 4U Server Chassis
site_author: HakoForge
site_url: https://docs.hakoforge.com

# Repository information
repo_name: /HakoForge/HakoCore
repo_url: https://github.com/HakoForge/HakoCore
edit_uri: edit/main/docs/

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Welcome: welcome.md
    - Safety & Cautions: cautions.md
    - Powerboard Connections: connections.md
    - Component Installation: components.md
    - Chassis Accessories: accessories.md
    - Chassis Fans: fans.md
    - Hako Foundry: foundry.md
  - Hardware Guide:
    - Cage Installation: hardware/cage-installation.md
    - Exploded View: hardware/exploded-view.md
    - Fan Installation: hardware/fan-installation.md
    - Lid Removal: hardware/panel-removal.md
    - PCB Installation: hardware/pcb-installation.md
    - Powerboard: hardware/powerboard.md
    - Power Harness: hardware/power-harness.md
    - SAS Routing: hardware/wire-routing.md
  - Backplanes:
    - 4-HDD Backplane: backplanes/4-hdd-backplane.md
    - 12-SSD Backplane: backplanes/12-ssd-backplane.md
    - 4-U.2 Backplane: backplanes/4-u.2-backplane.md
    - Mixed 4-Bay Backplane: backplanes/mixed-4-bay-backplane.md
  - Specifications: specifications.md
  - Support:
    - Warranty: warranty.md

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  logo: Logo.png
  favicon: imgs/Hako_Logo.ico

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - tables
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - glightbox

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_js:
  - javascripts/extra.js

# Footer
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:help@hakoforge.com
    - icon: fontawesome/brands/github
      link: https://github.com/hakoforge
  version:
    provider: mike